// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace bookkeepingAPI.Migrations
{
    [DbContext(typeof(bkcontext))]
    [Migration("20201102050044_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("bookkeepingAPI.Models.Cashbook", b =>
                {
                    b.Property<int>("receipt_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("cashInHand")
                        .HasColumnType("INTEGER");

                    b.Property<string>("details")
                        .HasColumnType("TEXT");

                    b.Property<int>("salesCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("receipt_no");

                    b.ToTable("Cashbook");
                });

            modelBuilder.Entity("bookkeepingAPI.Models.Contacts", b =>
                {
                    b.Property<int>("contact_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("contact_name")
                        .HasColumnType("TEXT");

                    b.HasKey("contact_no");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("bookkeepingAPI.Models.TodoItems", b =>
                {
                    b.Property<int>("item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("item_name")
                        .HasColumnType("TEXT");

                    b.HasKey("item_id");

                    b.ToTable("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
